/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON_COLON_EQ = 3,
  anon_sym_COLON_EQ = 4,
  anon_sym_PIPE = 5,
  anon_sym_COMMA = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_literal_token1 = 14,
  aux_sym_literal_token2 = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_literal_token3 = 17,
  anon_sym_QMARK = 18,
  aux_sym_special_sequence_token1 = 19,
  anon_sym_LT = 20,
  aux_sym_identifier_token1 = 21,
  anon_sym_GT = 22,
  sym_comment = 23,
  sym_grammar = 24,
  sym_rule = 25,
  sym_assignment = 26,
  sym_expression = 27,
  sym_sequence = 28,
  sym_term = 29,
  sym_group = 30,
  sym_optional = 31,
  sym_repetition = 32,
  sym_literal = 33,
  sym_special_sequence = 34,
  sym_identifier = 35,
  aux_sym_grammar_repeat1 = 36,
  aux_sym_expression_repeat1 = 37,
  aux_sym_sequence_repeat1 = 38,
  aux_sym_literal_repeat1 = 39,
  aux_sym_literal_repeat2 = 40,
  aux_sym_special_sequence_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON_COLON_EQ] = "::=",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_PIPE] = "|",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_literal_token1] = "literal_token1",
  [aux_sym_literal_token2] = "literal_token2",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_literal_token3] = "literal_token3",
  [anon_sym_QMARK] = "\?",
  [aux_sym_special_sequence_token1] = "special_sequence_token1",
  [anon_sym_LT] = "<",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_GT] = ">",
  [sym_comment] = "comment",
  [sym_grammar] = "grammar",
  [sym_rule] = "rule",
  [sym_assignment] = "assignment",
  [sym_expression] = "expression",
  [sym_sequence] = "sequence",
  [sym_term] = "term",
  [sym_group] = "group",
  [sym_optional] = "optional",
  [sym_repetition] = "repetition",
  [sym_literal] = "literal",
  [sym_special_sequence] = "special_sequence",
  [sym_identifier] = "identifier",
  [aux_sym_grammar_repeat1] = "grammar_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_literal_repeat1] = "literal_repeat1",
  [aux_sym_literal_repeat2] = "literal_repeat2",
  [aux_sym_special_sequence_repeat1] = "special_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON_COLON_EQ] = anon_sym_COLON_COLON_EQ,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_literal_token1] = aux_sym_literal_token1,
  [aux_sym_literal_token2] = aux_sym_literal_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_literal_token3] = aux_sym_literal_token3,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [aux_sym_special_sequence_token1] = aux_sym_special_sequence_token1,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym_comment] = sym_comment,
  [sym_grammar] = sym_grammar,
  [sym_rule] = sym_rule,
  [sym_assignment] = sym_assignment,
  [sym_expression] = sym_expression,
  [sym_sequence] = sym_sequence,
  [sym_term] = sym_term,
  [sym_group] = sym_group,
  [sym_optional] = sym_optional,
  [sym_repetition] = sym_repetition,
  [sym_literal] = sym_literal,
  [sym_special_sequence] = sym_special_sequence,
  [sym_identifier] = sym_identifier,
  [aux_sym_grammar_repeat1] = aux_sym_grammar_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_literal_repeat1] = aux_sym_literal_repeat1,
  [aux_sym_literal_repeat2] = aux_sym_literal_repeat2,
  [aux_sym_special_sequence_repeat1] = aux_sym_special_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_special_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_grammar] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_optional] = {
    .visible = true,
    .named = true,
  },
  [sym_repetition] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_special_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_grammar_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_special_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assignment = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assignment] = "assignment",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assignment, 1},
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '"', 27,
        '\'', 22,
        '(', 16,
        ')', 17,
        ',', 15,
        ':', 6,
        ';', 10,
        '<', 35,
        '=', 11,
        '>', 37,
        '?', 31,
        '[', 18,
        '\\', 8,
        ']', 19,
        '{', 20,
        '|', 14,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '(') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == '?') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(38);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON_COLON_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_literal_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_literal_token1);
      if (lookahead == '(') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '(' &&
          lookahead != '\\') ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_literal_token1);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_literal_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_literal_token3);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_literal_token3);
      if (lookahead == '(') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_literal_token3);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      if (lookahead == '(') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '?') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_special_sequence_token1);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON_COLON_EQ] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_literal_token2] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_grammar] = STATE(46),
    [sym_rule] = STATE(27),
    [sym_identifier] = STATE(30),
    [aux_sym_grammar_repeat1] = STATE(27),
    [anon_sym_LT] = ACTIONS(5),
    [aux_sym_identifier_token1] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_term,
    STATE(14), 1,
      sym_sequence,
    STATE(36), 1,
      sym_expression,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [45] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_term,
    STATE(14), 1,
      sym_sequence,
    STATE(41), 1,
      sym_expression,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [90] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_term,
    STATE(14), 1,
      sym_sequence,
    STATE(45), 1,
      sym_expression,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [135] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_term,
    STATE(14), 1,
      sym_sequence,
    STATE(44), 1,
      sym_expression,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [180] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(10), 1,
      sym_term,
    STATE(26), 1,
      sym_sequence,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [222] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_QMARK,
    STATE(23), 1,
      sym_term,
    STATE(16), 6,
      sym_group,
      sym_optional,
      sym_repetition,
      sym_literal,
      sym_special_sequence,
      sym_identifier,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_COLON_COLON_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_COLON_COLON_EQ,
      anon_sym_COLON_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [297] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_sequence_repeat1,
    ACTIONS(25), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [317] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_sequence_repeat1,
    ACTIONS(29), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [337] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_sequence_repeat1,
    ACTIONS(34), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [357] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_expression_repeat1,
    ACTIONS(36), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      aux_sym_expression_repeat1,
    ACTIONS(40), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_expression_repeat1,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 7,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_QMARK,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [579] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      aux_sym_identifier_token1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_identifier,
    STATE(28), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [599] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    STATE(28), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [619] = 4,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      sym_comment,
    STATE(31), 1,
      aux_sym_literal_repeat2,
    ACTIONS(77), 2,
      aux_sym_literal_token2,
      aux_sym_literal_token3,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(2), 1,
      sym_assignment,
    ACTIONS(83), 3,
      anon_sym_EQ,
      anon_sym_COLON_COLON_EQ,
      anon_sym_COLON_EQ,
  [645] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym_literal_repeat2,
    ACTIONS(85), 2,
      aux_sym_literal_token2,
      aux_sym_literal_token3,
  [659] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_SQUOTE,
    STATE(32), 1,
      aux_sym_literal_repeat1,
    ACTIONS(92), 2,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
  [673] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      aux_sym_literal_repeat1,
    ACTIONS(97), 2,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
  [687] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      aux_sym_literal_repeat2,
    ACTIONS(99), 2,
      aux_sym_literal_token2,
      aux_sym_literal_token3,
  [701] = 4,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym_literal_repeat1,
    ACTIONS(101), 2,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_SEMI,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [727] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_QMARK,
    ACTIONS(109), 1,
      aux_sym_special_sequence_token1,
    STATE(39), 1,
      aux_sym_special_sequence_repeat1,
  [740] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_QMARK,
    ACTIONS(113), 1,
      aux_sym_special_sequence_token1,
    STATE(38), 1,
      aux_sym_special_sequence_repeat1,
  [753] = 4,
    ACTIONS(81), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(118), 1,
      aux_sym_special_sequence_token1,
    STATE(38), 1,
      aux_sym_special_sequence_repeat1,
  [766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 3,
      ts_builtin_sym_end,
      anon_sym_LT,
      aux_sym_identifier_token1,
  [775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_GT,
  [789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      aux_sym_identifier_token1,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
  [803] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
  [810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 261,
  [SMALL_STATE(9)] = 279,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 317,
  [SMALL_STATE(12)] = 337,
  [SMALL_STATE(13)] = 357,
  [SMALL_STATE(14)] = 376,
  [SMALL_STATE(15)] = 395,
  [SMALL_STATE(16)] = 410,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 440,
  [SMALL_STATE(19)] = 455,
  [SMALL_STATE(20)] = 470,
  [SMALL_STATE(21)] = 485,
  [SMALL_STATE(22)] = 500,
  [SMALL_STATE(23)] = 515,
  [SMALL_STATE(24)] = 530,
  [SMALL_STATE(25)] = 549,
  [SMALL_STATE(26)] = 565,
  [SMALL_STATE(27)] = 579,
  [SMALL_STATE(28)] = 599,
  [SMALL_STATE(29)] = 619,
  [SMALL_STATE(30)] = 633,
  [SMALL_STATE(31)] = 645,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 673,
  [SMALL_STATE(34)] = 687,
  [SMALL_STATE(35)] = 701,
  [SMALL_STATE(36)] = 715,
  [SMALL_STATE(37)] = 727,
  [SMALL_STATE(38)] = 740,
  [SMALL_STATE(39)] = 753,
  [SMALL_STATE(40)] = 766,
  [SMALL_STATE(41)] = 775,
  [SMALL_STATE(42)] = 782,
  [SMALL_STATE(43)] = 789,
  [SMALL_STATE(44)] = 796,
  [SMALL_STATE(45)] = 803,
  [SMALL_STATE(46)] = 810,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_sequence, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repetition, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_sequence, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(31),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_literal_repeat2, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_literal_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_special_sequence_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [132] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ebnf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ebnf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
